server:
  port: 0

spring:
  application:
    name: resourceServer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    shutdown:
      enabled: true